// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsEqOPjZeAhW3ITybWCIZ3MWFmgW2I6-M',
    appId: '1:406016823162:web:9d63628b24d701aac490c3',
    messagingSenderId: '406016823162',
    projectId: 'playon-abb70',
    authDomain: 'playon-abb70.firebaseapp.com',
    storageBucket: 'playon-abb70.firebasestorage.app',
    measurementId: 'G-L7JC7ZEPEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-xXPgUGeeNcs_IUsESDg972aJxmwKBNs',
    appId: '1:406016823162:android:564e4f9574b3301cc490c3',
    messagingSenderId: '406016823162',
    projectId: 'playon-abb70',
    storageBucket: 'playon-abb70.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB226L_4VvtVESolp00NXi0Bz7g5Vzi4hM',
    appId: '1:406016823162:ios:e62f8f91a291f128c490c3',
    messagingSenderId: '406016823162',
    projectId: 'playon-abb70',
    storageBucket: 'playon-abb70.firebasestorage.app',
    iosBundleId: 'com.example.playtrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB226L_4VvtVESolp00NXi0Bz7g5Vzi4hM',
    appId: '1:406016823162:ios:e62f8f91a291f128c490c3',
    messagingSenderId: '406016823162',
    projectId: 'playon-abb70',
    storageBucket: 'playon-abb70.firebasestorage.app',
    iosBundleId: 'com.example.playtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsEqOPjZeAhW3ITybWCIZ3MWFmgW2I6-M',
    appId: '1:406016823162:web:205012b932e6fe07c490c3',
    messagingSenderId: '406016823162',
    projectId: 'playon-abb70',
    authDomain: 'playon-abb70.firebaseapp.com',
    storageBucket: 'playon-abb70.firebasestorage.app',
    measurementId: 'G-BLY97CZ3K0',
  );

}